### PR TITLE
Decode text nodes before passing to React

### PR DESCRIPTION
**Pull request by aknuds1**
Text nodes must be decoded so that React doesn't escape character entities, such as `&gt;`.

### CODE REVIEW

**Comment by lithin** [comment]
This looks great!

**Comment by aknuds1** [comment]
@lithin :+1:

**Comment by mikenikles** [comment]
Thanks @aknuds1, could you please update your branch with the latest `master`? I'm happy to merge it.

**Comment by aknuds1** [comment]
@mikenikles Done.

**Comment by aknuds1** [comment]
@mikenikles Will you please merge this soon?

**Comment by mikenikles** [comment]
@aknuds1 Could you please update your branch one last time? My apologies for not being active with this project for so long. I'm now back and plan to push a release asap. Thanks

**Comment by aknuds1** [comment]
@mikenikles Done.

**Comment by mikenikles** [comment]
Thanks @aknuds1!

**Pull request merged**
