### PR TITLE
Create element keys per sequence

### PR DESCRIPTION
**Pull request by aknuds1**
Simplify code and make it more functional in style; generate element keys per sequence and not globally.

### CODE REVIEW

**Comment by aknuds1** [comment]
@mikenikles Could you please consider merging this?

**Comment by mikenikles** [comment]
Same as for #18, please update your branch and I'll include that PR in the next release.

**Comment by aknuds1** [comment]
@mikenikles Done.

**Comment by mikenikles** [comment]
@aknuds1 It looks like #18 causes merge conflicts with this PR. Do you mind updating this branch one more time?

**Comment by aknuds1** [comment]
Will do, once I have the time

**Comment by aknuds1** [comment]
@mikenikles Should be ready now.

**Comment by mikenikles** [comment]
Awesome @aknuds1!

**Pull request merged**
