### PR TITLE
Test with node 4 and 5 on travis

### PR DESCRIPTION
**Pull request by thangngoc89**

### CODE REVIEW

**Comment by mikenikles** [comment]
@thangngoc89 Why would you like to specify node 4 and 5 instead of the latest stable release?

**Comment by simon-lifelike** [comment]
Travis CI is using nvm to manage node versions, and as per the [nvm usage documentation](https://github.com/creationix/nvm#usage):

> - `stable`: this alias is deprecated, and only truly applies to `node` `v0.12` and earlier. Currently, this is an alias for `node`.

The version you want to test is probably `4`, which covers the latest version of LTS, and `node` which covers the latest stable. Eventually [additional aliases](https://github.com/creationix/nvm/issues/870) for LTS versions will be available.

**Comment by mikenikles** [comment]
Thanks @simon-lifelike! @thangngoc89 could you please merge the latest `master` into your branch so that I can resolve this PR? Cheers

**Comment by thangngoc89** [comment]
I rebased this branch to your master

**Comment by thangngoc89** [comment]
I added node 6 to build matrix.

**Comment by mikenikles** [comment]
@thangngoc89 Thanks so much, one last update from `master` and I'll be able to merge that PR.

**Comment by thangngoc89** [comment]
PR updated.

**Comment by mikenikles** [comment]
Thanks!

**Pull request merged**
